# Generated by Django 4.2.4 on 2023-08-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="ID",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="ID",
        ),
        migrations.AlterField(
            model_name="booking",
            name="No_of_geusts",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="menu",
            name="Inventory",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="booking",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="menu",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
            preserve_default=False,
        ),
    ]
